#!/usr/bin/env bats
# install.sh — pre-commit hook bootstrap (GH#167).
#
# Each test stages a throwaway repo skeleton with install.sh copied in,
# then exercises one of the four pre-commit-install paths from the issue's
# acceptance criteria:
#   1. pre-commit on PATH + .pre-commit-config.yaml present → installs hook.
#   2. pre-commit not on PATH → exit 0, prints skip line, no hook created.
#   3. existing hook with the 'pre-commit' framework marker → no-op.
#   4. stock-sample git hook → overwritten via `pre-commit install --overwrite`.

load 'helpers'

setup() {
  REPO="$BATS_TEST_TMPDIR/repo"
  mkdir -p "$REPO/bin" "$REPO/runners/lib" "$REPO/.git/hooks"
  cp "$LOOP_ROOT/install.sh" "$REPO/install.sh"
  chmod +x "$REPO/install.sh"
  # install.sh chmods these globs; touch placeholders so the script doesn't
  # error on a `chmod: no such file` from an empty glob.
  : >"$REPO/bin/st"
  : >"$REPO/runners/run-loop.sh"
  : >"$REPO/runners/lib/_preamble.sh"
  # Direct the symlink target into bats' tmpdir, not the user's $HOME/.local/bin.
  export LOOP_INSTALL_DIR="$BATS_TEST_TMPDIR/bin"
}

# Build a `pre-commit` stub that mimics `pre-commit install [--overwrite]`:
# writes `.git/hooks/pre-commit` with the framework marker so onboard's
# check_pre_commit_hook would pass against the result. Records argv to a log
# so tests can assert how install.sh invoked it.
_install_pre_commit_stub() {
  local stub_dir="$BATS_TEST_TMPDIR/path-stubs"
  mkdir -p "$stub_dir"
  export PRE_COMMIT_LOG="$BATS_TEST_TMPDIR/pre-commit.log"
  : >"$PRE_COMMIT_LOG"
  cat >"$stub_dir/pre-commit" <<STUB
#!/usr/bin/env bash
echo "\$*" >>"$PRE_COMMIT_LOG"
hook="\$PWD/.git/hooks/pre-commit"
mkdir -p "\$(dirname "\$hook")"
printf '#!/usr/bin/env bash\n# File generated by pre-commit\nexec pre-commit hook-impl "\$@"\n' >"\$hook"
chmod +x "\$hook"
exit 0
STUB
  chmod +x "$stub_dir/pre-commit"
  export STUB_PATH="$stub_dir:$PATH"
}

# Stage a minimal .github/workflows/ci.yml so check_lint_tool_versions can
# parse SHELLCHECK_VERSION / SHFMT_VERSION (matches the format in the real
# ci.yml: leading whitespace + `=` separator).
_write_fake_ci_yml() {
  local sc_ver="$1" sf_ver="$2"
  mkdir -p "$REPO/.github/workflows"
  cat >"$REPO/.github/workflows/ci.yml" <<CI
name: ci
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          SHELLCHECK_VERSION=v${sc_ver}
          SHFMT_VERSION=v${sf_ver}
CI
}

# Stub for shellcheck: prints the matching `--version` block format
# (`version: X.Y.Z`) so the installer's awk parse picks up the right line.
_install_shellcheck_stub() {
  local version="$1" stub_dir="$BATS_TEST_TMPDIR/lint-stubs"
  mkdir -p "$stub_dir"
  cat >"$stub_dir/shellcheck" <<STUB
#!/usr/bin/env bash
if [ "\$1" = "--version" ]; then
  printf 'ShellCheck - shell script analysis tool\nversion: %s\nlicense: GPL-3\n' "$version"
  exit 0
fi
exit 0
STUB
  chmod +x "$stub_dir/shellcheck"
  STUB_PATH="$stub_dir:${STUB_PATH:-$PATH}"
  export STUB_PATH
}

# Stub for shfmt: prints exactly `vX.Y.Z\n` from `--version`, mirroring
# the upstream binary's output format that install.sh parses.
_install_shfmt_stub() {
  local version="$1" stub_dir="$BATS_TEST_TMPDIR/lint-stubs"
  mkdir -p "$stub_dir"
  cat >"$stub_dir/shfmt" <<STUB
#!/usr/bin/env bash
if [ "\$1" = "--version" ]; then
  printf '%s\n' "$version"
  exit 0
fi
exit 0
STUB
  chmod +x "$stub_dir/shfmt"
  STUB_PATH="$stub_dir:${STUB_PATH:-$PATH}"
  export STUB_PATH
}

@test "install.sh: installs pre-commit hook when pre-commit on PATH and config present" {
  : >"$REPO/.pre-commit-config.yaml"
  _install_pre_commit_stub
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  [ -f "$REPO/.git/hooks/pre-commit" ]
  grep -qi 'pre-commit' "$REPO/.git/hooks/pre-commit"
  echo "$output" | grep -qF "[install] ran 'pre-commit install'"
  # Stub was invoked exactly once, plain `install` (no --overwrite).
  [ "$(wc -l <"$PRE_COMMIT_LOG" | tr -d ' ')" = 1 ]
  grep -q '^install$' "$PRE_COMMIT_LOG"
}

@test "install.sh: skips pre-commit install when pre-commit is not on PATH" {
  : >"$REPO/.pre-commit-config.yaml"
  cd "$REPO"
  # Strip pre-commit from PATH but keep the basics install.sh + chmod need.
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="/usr/bin:/bin" bash install.sh
  [ "$status" -eq 0 ]
  [ ! -e "$REPO/.git/hooks/pre-commit" ]
  echo "$output" | grep -qF '[install] skipping pre-commit install'
}

@test "install.sh: skips when .pre-commit-config.yaml is missing" {
  _install_pre_commit_stub
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  [ ! -e "$REPO/.git/hooks/pre-commit" ]
  echo "$output" | grep -qF '[install] skipping pre-commit install'
  # Stub was never invoked.
  [ ! -s "$PRE_COMMIT_LOG" ]
}

@test "install.sh: leaves an existing pre-commit-framework hook untouched" {
  : >"$REPO/.pre-commit-config.yaml"
  printf '#!/usr/bin/env bash\n# File generated by pre-commit\n# user customisation here\nexit 0\n' \
    >"$REPO/.git/hooks/pre-commit"
  chmod +x "$REPO/.git/hooks/pre-commit"
  local before
  before=$(cat "$REPO/.git/hooks/pre-commit")
  _install_pre_commit_stub
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  # Hook content unchanged — the existing framework hook was preserved.
  [ "$(cat "$REPO/.git/hooks/pre-commit")" = "$before" ]
  # Stub was not invoked (no install or overwrite happened).
  [ ! -s "$PRE_COMMIT_LOG" ]
  # And install.sh logged the deliberate skip — distinguishes "explicit no-op"
  # from "no pre-commit logic ran at all".
  echo "$output" | grep -qF '[install] skipping pre-commit install'
}

@test "install.sh: overwrites the stock-sample git hook" {
  : >"$REPO/.pre-commit-config.yaml"
  # Git ships this as the default sample; install.sh should treat it as
  # safe to replace.
  printf '#!/bin/sh\n#\n# An example hook script to verify what is about to be committed.\nexit 0\n' \
    >"$REPO/.git/hooks/pre-commit"
  chmod +x "$REPO/.git/hooks/pre-commit"
  _install_pre_commit_stub
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  # New hook installed by stub — has the framework marker.
  grep -qi 'pre-commit' "$REPO/.git/hooks/pre-commit"
  ! grep -qi 'example hook script' "$REPO/.git/hooks/pre-commit"
  # Stub was invoked with --overwrite.
  grep -q -- '--overwrite' "$PRE_COMMIT_LOG"
}

@test "install.sh: warns when installed shellcheck version differs from CI pin" {
  : >"$REPO/.pre-commit-config.yaml"
  _write_fake_ci_yml "0.11.0" "3.13.1"
  _install_pre_commit_stub
  _install_shellcheck_stub "0.10.0"  # mismatched
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  echo "$output" | grep -qF '[install] WARN: shellcheck 0.10.0 installed but CI pins v0.11.0'
}

@test "install.sh: warns when installed shfmt version differs from CI pin" {
  : >"$REPO/.pre-commit-config.yaml"
  _write_fake_ci_yml "0.11.0" "3.13.1"
  _install_pre_commit_stub
  _install_shfmt_stub "v3.12.0"  # mismatched
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  echo "$output" | grep -qF '[install] WARN: shfmt v3.12.0 installed but CI pins v3.13.1'
}

@test "install.sh: silent when shellcheck and shfmt versions match CI pin" {
  : >"$REPO/.pre-commit-config.yaml"
  _write_fake_ci_yml "0.11.0" "3.13.1"
  _install_pre_commit_stub
  _install_shellcheck_stub "0.11.0"
  _install_shfmt_stub "v3.13.1"
  cd "$REPO"
  run env LOOP_INSTALL_DIR="$LOOP_INSTALL_DIR" PATH="$STUB_PATH" bash install.sh
  [ "$status" -eq 0 ]
  # No version-mismatch warning when both tools match. Match only the
  # tool-specific WARN prefix so the unrelated `LOOP_INSTALL_DIR not on
  # $PATH` warning (which always fires in bats) doesn't trip the assertion.
  ! echo "$output" | grep -qE '^\[install\] WARN: (shellcheck|shfmt) '
}
